<h1><u><b>HEALTHCARE FRAUD DETECTION ANALYSIS<b><u></h1>

In [1]:
## Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Loading Datasets

In [4]:
##Datasets
provider_data=pd.read_csv('Data\provider_fraud_detection_data.csv')
Beneficiary_data=pd.read_csv('Data\Train_Beneficiarydata-1542865627584.csv')
Inpatient_data= pd.read_csv('Data\Train_Inpatientdata-1542865627584.csv')
Outpatient_data=pd.read_csv('Data\Train_Outpatientdata-1542865627584.csv')

-- <b>Data Preprocessing<b>
<ol>
<li>Check missing values</li>
<li>Duplicates</li>
<li>display total number of rows</li>
<ol>

In [5]:
#data_preprocessing function 
def data_preprocessing(data):
    # Check for missing values
    missing_values = data.isnull().sum().sum()
    print("Missing Values:")
    print(missing_values)
    print()

    # Check for duplicates
    duplicates = data.duplicated().sum()
    print("Number of Duplicates:", duplicates)
    print()

    # Display total number of rows
    num_rows = data.shape[0]
    print("Total Number of Rows:", num_rows)
    print()



    # Statistical summary
    print("Statistical Summary:")
    print(data.describe(include='all'))

<h2><u><b>Provider Data</b><u></h2>

In [6]:
provider_data

      Provider PotentialFraud
0     PRV51001             No
1     PRV51003            Yes
2     PRV51004             No
3     PRV51005            Yes
4     PRV51007             No
...        ...            ...
5405  PRV57759             No
5406  PRV57760             No
5407  PRV57761             No
5408  PRV57762             No
5409  PRV57763             No

[5410 rows x 2 columns]

In [7]:
data_preprocessing(provider_data)

Missing Values:
0

Number of Duplicates: 0

Total Number of Rows: 5410

Statistical Summary:
        Provider PotentialFraud
count       5410           5410
unique      5410              2
top     PRV51001             No
freq           1           4904

<h2><u><b>Out patient data<b></u><h2>

In [8]:
Outpatient_data

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,...,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56409
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,79380
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,NaN,NaN,2723,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,BENE11004,CLM121801,2009-01-06,2009-01-06,PRV56011,40,PHY334319,NaN,NaN,71988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
4,BENE11004,CLM150998,2009-01-22,2009-01-22,PRV56011,200,PHY403831,NaN,NaN,82382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,71947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517732,BENE159198,CLM510792,2009-08-06,2009-08-06,PRV53699,800,PHY364188,PHY364188,PHY385752,2163,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517733,BENE159198,CLM551294,2009-08-29,2009-08-29,PRV53702,400,PHY423019,PHY332284,NaN,07041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517734,BENE159198,CLM596444,2009-09-24,2009-09-24,PRV53676,60,PHY361063,NaN,NaN,V570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517735,BENE159198,CLM636992,2009-10-18,2009-10-18,PRV53689,70,PHY403198,NaN,PHY419379,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517736,BENE159198,CLM686139,2009-11-17,2009-11-18,PRV53689,80,PHY419379,NaN,PHY419379,78900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [ ]:
data_preprocessing(Outpatient_data)

In [ ]:
Outpatient_data_info = pd.DataFrame(data=Outpatient_data.columns, columns=['Column Name'])
Outpatient_data_info['Data Type'] = Outpatient_data.dtypes.values
Outpatient_data_info['No. of Unique Values'] = Outpatient_data.nunique().values
Outpatient_data_info['Count of Missing Values'] = Outpatient_data.isna().sum().values
Outpatient_data_info['Percent of Missing Values'] = (round(Outpatient_data.isna().sum() / len(Outpatient_data) * 100)).values

In [ ]:
Outpatient_data_info

''' check for relevant columns

<h2><u><b>In Patient data<b></u></h2>

In [ ]:
Inpatient_data

In [ ]:
data_preprocessing(Inpatient_data)

In [ ]:
Inpatient_data_info = pd.DataFrame(data=Inpatient_data.columns, columns=['Column Name'])
Inpatient_data_info['Data Type'] = Inpatient_data.dtypes.values
Inpatient_data_info['No. of Unique Values'] = Inpatient_data.nunique().values
Inpatient_data_info['Count of Missing Values'] = Inpatient_data.isna().sum().values
Inpatient_data_info['Percent of Missing Values'] = (round(Inpatient_data.isna().sum() / len(Inpatient_data) * 100)).values

In [ ]:
Inpatient_data_info

<h2><u><b>Beneficiary Data<b><u></h2>

In [ ]:
Beneficiary_data

In [ ]:
data_preprocessing(Beneficiary_data)

In [ ]:
Beneficiary_data_info = pd.DataFrame(data=Beneficiary_data.columns, columns=['Column Name'])
Beneficiary_data_info['Data Type'] = Beneficiary_data.dtypes.values
Beneficiary_data_info['No. of Unique Values'] = Beneficiary_data.nunique().values
Beneficiary_data_info['Count of Missing Values'] = Beneficiary_data.isna().sum().values
Beneficiary_data_info['Percent of Missing Values'] = (round(Beneficiary_data.isna().sum() / len(Beneficiary_data) * 100)).values

In [ ]:
Beneficiary_data_info

<p>Checking for common columns in outpatients and inpatient dataset

In [ ]:
col_outpatient=[]
for o in Outpatient_data.columns:
    if o in Inpatient_data.columns:
        col_outpatient.append(o)

#Checking each of the columns in the Inpatient dataset if they are present in the Outpatient dataset
col_inpatient=[]
for i in Inpatient_data.columns:
    if i in Outpatient_data.columns:
        col_inpatient.append(i)
print("Cols of Outpatient dataset also present in Inpatient dataset",len(col_outpatient))
print("Cols of Inpatient dataset also present in Outpatient dataset",len(col_inpatient))

#Checking for common column names in the outpatient and the inpatient datasets 
c_s= set(col_outpatient).intersection(set(col_inpatient))
c_s= list(c_s)
print("Common columns between the outpatient and the inpatient datasets",len(c_s))

In [ ]:
c_s

In [ ]:
Allpatientdata=pd.merge(Outpatient_data,Inpatient_data,
                              left_on=['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
       'InscClaimAmtReimbursed', 'AttendingPhysician', 'OperatingPhysician',
       'OtherPhysician', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2',
       'ClmDiagnosisCode_3', 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5',
       'ClmDiagnosisCode_6', 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8',
       'ClmDiagnosisCode_9', 'ClmDiagnosisCode_10', 'ClmProcedureCode_1',
       'ClmProcedureCode_2', 'ClmProcedureCode_3', 'ClmProcedureCode_4',
       'ClmProcedureCode_5', 'ClmProcedureCode_6', 'DeductibleAmtPaid',
       'ClmAdmitDiagnosisCode'],
                              right_on=['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
       'InscClaimAmtReimbursed', 'AttendingPhysician', 'OperatingPhysician',
       'OtherPhysician', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2',
       'ClmDiagnosisCode_3', 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5',
       'ClmDiagnosisCode_6', 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8',
       'ClmDiagnosisCode_9', 'ClmDiagnosisCode_10', 'ClmProcedureCode_1',
       'ClmProcedureCode_2', 'ClmProcedureCode_3', 'ClmProcedureCode_4',
       'ClmProcedureCode_5', 'ClmProcedureCode_6', 'DeductibleAmtPaid',
       'ClmAdmitDiagnosisCode']
                              ,how='outer')

In [ ]:
Allpatientdata